#!/bin/bash
set -e
cd "$(dirname "$0")"
TOK=$(grep '^PF_WATCH_TOKEN=' ~/.config/paceforge/env | cut -d= -f2)
cat > source/Secrets.mc << MC
// GENERATED by build.sh — gitignored (carries the watch-targets token).
const TARGETS_URL = "https://claude-dev-vperrod.westeurope.cloudapp.azure.com/paceforge/api/watch-targets?k=$TOK";
MC
SDK=~/tools/connectiq-sdk-9.2.0/bin/monkeyc
KEY=~/.Garmin/ConnectIQ/developer_key.der
$SDK -o build/PaceForgeClass-fenix7x.prg -f monkey.jungle -y $KEY -d fenix7x -w -r
$SDK -o build/PaceForgeClass-fenix7xpro.prg -f monkey.jungle -y $KEY -d fenix7xpro -w -r
echo built
