#!/bin/bash
# Bake the watch-race URL (with token) into a gitignored source file, then
# compile both targets. Token comes from ~/.config/paceforge/env.
set -e
cd "$(dirname "$0")"
TOK=$(grep '^PF_WATCH_TOKEN=' ~/.config/paceforge/env | cut -d= -f2)
cat > source/Secrets.mc << MC
// GENERATED by build.sh — gitignored (carries the watch-race token).
const RACE_URL = "https://claude-dev-vperrod.westeurope.cloudapp.azure.com/paceforge/api/watch-race?k=$TOK";
MC
SDK=~/tools/connectiq-sdk-9.2.0/bin/monkeyc
KEY=~/.Garmin/ConnectIQ/developer_key.der
$SDK -o build/PaceForgeRace-fenix7x.prg -f monkey.jungle -y $KEY -d fenix7x -w -r
$SDK -o build/PaceForgeRace-fenix7xpro.prg -f monkey.jungle -y $KEY -d fenix7xpro -w -r
echo "built"
